In [1]:
import os
os.getcwd()
os.chdir('D:\ML pratice dataset')
os.getcwd()

'D:\\ML pratice dataset'

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("student-mat.csv", sep=";")

In [5]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [6]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]

In [7]:
data

     G1  G2  G3  studytime  failures  absences
0     5   6   6          2         0         6
1     5   5   6          2         0         4
2     7   8  10          2         3        10
3    15  14  15          3         0         2
4     6  10  10          2         0         4
..   ..  ..  ..        ...       ...       ...
390   9   9   9          2         2        11
391  14  16  16          1         0         3
392  10   8   7          1         3         3
393  11  12  10          1         0         0
394   8   9   9          1         0         5

[395 rows x 6 columns]

In [8]:
predict = "G3"

X = np.array(data.drop([predict], 1)) # Features

In [9]:
X

array([[ 5,  6,  2,  0,  6],
       [ 5,  5,  2,  0,  4],
       [ 7,  8,  2,  3, 10],
       ...,
       [10,  8,  1,  3,  3],
       [11, 12,  1,  0,  0],
       [ 8,  9,  1,  0,  5]], dtype=int64)

In [10]:
y = np.array(data[predict]) # Labels

In [11]:
y

array([ 6,  6, 10, 15, 10, 15, 11,  6, 19, 15,  9, 12, 14, 11, 16, 14, 14,
       10,  5, 10, 15, 15, 16, 12,  8,  8, 11, 15, 11, 11, 12, 17, 16, 12,
       15,  6, 18, 15, 11, 13, 11, 12, 18, 11,  9,  6, 11, 20, 14,  7, 13,
       13, 10, 11, 13, 10, 15, 15,  9, 16, 11, 11,  9,  9, 10, 15, 12,  6,
        8, 16, 15, 10,  5, 14, 11, 10, 10, 11, 10,  5, 12, 11,  6, 15, 10,
        8,  6, 14, 10,  7,  8, 18,  6, 10, 14, 10, 15, 10, 14,  8,  5, 17,
       14,  6, 18, 11,  8, 18, 13, 16, 19, 10, 13, 19,  9, 16, 14, 13,  8,
       13, 15, 15, 13, 13,  8, 12, 11,  9,  0, 18,  0,  0, 12, 11,  0,  0,
        0,  0, 12, 15,  0,  9, 11, 13,  0, 11,  0, 11,  0, 10,  0, 14, 10,
        0, 12,  8, 13, 10, 15, 12,  0,  7,  0, 10,  7, 12, 10, 16,  0, 14,
        0, 16, 10,  0,  9,  9, 11,  6,  9, 11,  8, 12, 17,  8, 12, 11, 11,
       15,  9, 10, 13,  9,  8, 10, 14, 15, 16, 10, 18, 10, 16, 10, 10,  6,
       11,  9,  7, 13, 10,  7,  8, 13, 14,  8, 10, 15,  4,  8,  8, 10,  6,
        0, 17, 13, 14,  7, 15, 12,  9, 12, 14, 11,  9, 13,  6, 10, 13, 12,
       11,  0, 12, 12,  0, 12,  0, 18, 13,  8,  5, 15,  8, 10,  8,  8, 12,
        8, 13, 11, 14,  0, 18,  8, 12,  9,  0, 17, 10, 11, 10,  0,  9, 14,
       11, 14, 10, 12,  9,  9,  8, 10,  8, 10, 12, 10, 11, 11, 19, 12, 14,
       15, 11, 15, 13, 18, 14, 11,  0,  8, 14, 16, 11, 10, 14, 18, 13, 12,
       18,  8, 12, 10,  0, 13, 11, 11, 13, 11,  0,  9, 10, 11, 13,  9, 11,
       15, 15, 11, 16, 10,  9, 14,  8, 14,  0,  0,  0, 15, 13,  0, 17, 10,
       11,  0, 15,  0, 10, 14, 16,  9, 15, 13,  8, 13,  8,  8, 11,  9, 13,
       11, 10, 16, 13, 12, 10, 15, 12, 10, 13,  0, 10, 11,  9, 12, 11,  5,
       19, 10, 15, 10, 15, 10, 14,  7, 10,  0,  5, 10,  6,  0,  8,  0,  9,
       16,  7, 10,  9], dtype=int64)

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.5)

In [40]:
model=LinearRegression()

In [41]:
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [42]:
#from sklearn.metrics import accuracy_score

In [43]:
#predictions=model.predict(x_test)

In [44]:
#print(accuracy_score(y_test,predictions))

In [45]:
acc = model.score(x_test, y_test)

In [46]:
print(acc)

0.8228347328830838

In [47]:
predictions=model.predict(x_test)

In [48]:
for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])

8.65268440222202 [10  9  3  0  7] 9
9.26677416492575 [ 9 10  3  0  0] 0
6.423973449881097 [7 7 1 0 3] 8
8.801221557224553 [9 9 1 0 8] 10
15.723018797962444 [17 15  1  0  4] 16
15.317630027654277 [16 15  2  0  0] 15
10.625681299797021 [11 11  3  0  3] 11
5.378106815224332 [7 6 1 0 0] 0
6.79901843773008 [ 6  8  1  3 16] 8
-1.504229592154661 [5 0 1 3 0] 0
8.70887328713089 [10  9  2  0  4] 9
11.78565872581266 [14 11  1  0 18] 13
11.984588434668291 [13 12  3  0  6] 12
19.89785161358929 [18 19  1  0 10] 19
19.472920276201258 [19 19  4  0  4] 20
15.11469217617808 [14 15  2  0  4] 15
4.073113444182503 [5 5 2 0 4] 6
7.108593794519203 [7 8 4 0 8] 8
16.18922203355914 [14 16  1  0  3] 16
8.607404361392792 [9 9 2 0 6] 10
11.417566901228998 [12 11  1  0 16] 11
16.419685547219913 [16 16  1  0  0] 15
10.029996543633434 [10 10  2  0 17] 10
4.229633694289757 [6 5 2 0 4] 6
7.542645787551665 [8 8 2 0 8] 6
8.874027260238357 [10  9  2  0 10] 10
10.285115137397936 [ 9 11  3  0  2] 11
5.091454416654689 [5 6 2 0 6] 6
9.515642685126666 [ 9 10  2  0  4] 10
11.8469601237454 [13 12  3  0  1] 12
12.700797751005615 [10 13  1  0  4] 14
9.092499536173849 [ 7 10  2  0  0] 11
13.856116406505196 [13 14  3  0  4] 14
10.838390434813144 [12 11  2  0  0] 12
11.851534576948577 [14 12  2  1  0] 12
9.684233550897597 [10 10  2  1 14] 9
11.783925704271525 [11 12  1  0  0] 10
13.150329001603296 [12 13  2  0 14] 12
5.515735126147222 [7 6 1 0 5] 7
12.9754037449559 [13 13  3  0  7] 14
9.718580536602861 [11 10  2  0  0] 10
13.867025250584838 [12 14  1  0  0] 15
11.975467779023857 [11 12  2  0 12] 11
10.663195302235929 [10  9  2  0 75] 9
12.875072379757516 [12 13  2  0  4] 13
8.274849544860347 [9 9 1 2 8] 9
13.884779629229488 [13 14  2  0  0] 15
5.939444585682655 [7 7 2 1 0] 0
10.736921509075048 [11 11  2  0  2] 10
7.320165368995612 [ 8  8  4  0 10] 8
9.857346408065466 [11 10  1  0  0] 10
7.910737612135328 [10  8  2  0 10] 8
10.52307481351921 [10 11  4  0 10] 11
10.81430166529203 [13 11  2  1  3] 11
13.306849251710549 [13 13  2  0 14] 14
4.9245405058739316 [8 6 2 2 2] 5
8.328763308689789 [ 9  9  2  2 15] 9
10.820636056168496 [11 11  1  0  0] 10
9.497888306482018 [ 8 10  1  0  4] 10
14.224208231088857 [15 14  3  0  6] 14
7.256480321626242 [9 8 4 0 2] 8
12.132474961775328 [15 12  3  0  0] 14
-0.6969171949637043 [6 0 2 0 0] 0
9.449682516677866 [10 10  4  0  6] 11
16.178313189479496 [15 16  3  0  7] 15
7.634937991094366 [8 9 1 3 0] 10
5.569592823425704 [8 7 2 3 0] 0
18.824459316747948 [18 18  1  0  6] 18
7.754217362028074 [ 9  8  2  0 10] 8
15.161109777547024 [15 15  2  0  0] 15
6.993322566206059 [9 8 1 3 6] 10
8.562124320563566 [8 9 1 0 5] 9
12.75584907537477 [10 13  1  0  6] 13
8.395832786916383 [8 9 2 0 4] 10
4.6436561875981415 [ 6  5  1  0 14] 5
15.21616110191618 [15 15  2  0  2] 14
11.353310603902525 [11 12  3  1  4] 11
10.681870184705891 [11 11  2  0  0] 10
8.662455685761948 [9 9 2 0 8] 9
11.335556225257877 [10 12  2  1  4] 12
18.732111046654282 [19 18  2  0  2] 18
8.570107415668286 [10  9  3  0  4] 9
5.514597565607508 [ 7  6  2  0 10] 6
15.004589527439768 [14 15  2  0  0] 15
11.076350110934419 [13 11  3  0  8] 11
16.179450750019207 [15 16  2  0  2] 16
16.040684878556604 [15 16  3  0  2] 18
14.903120601701671 [13 15  2  0  2] 16
10.736921509075048 [11 11  2  0  2] 11
15.594024210039771 [16 15  1  0  5] 16
12.49607171109421 [11 13  4  0  6] 14
12.921003048482238 [10 13  1  0 12] 12
9.359122435019414 [ 8 10  2  0  4] 10
12.096966204486032 [13 12  1  0  0] 12
3.8563450393693426 [6 5 2 1 0] 0
13.006366299803938 [14 13  3  1 12] 13
12.159513691315688 [12 12  2  0 13] 13
14.570537534407308 [13 15  4  0  0] 15
12.13198802913111 [12 12  2  0 12] 11
6.884979855141037 [6 8 1 1 0] 8
9.689917313878569 [11 10  3  0  4] 11
-0.2273564446419445 [9 0 2 0 0] 0
8.321238895467369 [10  9  4  0  0] 0
11.750065651210479 [13 12  2  1  2] 12
14.485147366953452 [15 14  2  1 20] 13
12.759285968038233 [11 13  1  1 10] 13
9.672162935233919 [10 10  2  0  4] 10
7.496228186182725 [ 7  8  2  0 12] 8
15.022343906084417 [15 15  3  0  0] 15
12.187039353500266 [12 12  2  0 14] 12
16.333695879047035 [16 16  4  0 12] 16
8.424496009640675 [8 9 1 0 0] 8
18.8795106411171 [18 18  1  0  8] 18
14.418025426920618 [15 14  2  0  8] 14
10.368829684491384 [ 9 11  2  0  0] 12
12.647479448177592 [13 12  1  0 20] 12
8.51505609129913 [10  9  3  0  2] 8
11.868802022949007 [12 12  2  1 12] 13
5.891323113191385 [ 8  6  2  0 18] 7
18.53829385082252 [19 18  3  0  0] 19
6.035201497677861 [7 7 4 0 4] 6
6.359150841972012 [8 7 2 0 0] 8
14.986835148795121 [13 15  1  0  0] 15
15.225932385456106 [14 15  1  0  3] 16
10.635452583336951 [10 11  2  0  4] 9
12.805703569407173 [12 13  1  1  6] 14
8.442250388285323 [9 9 2 0 0] 10
4.450976552306096 [6 5 1 0 7] 6
3.717579167906738 [6 5 3 1 0] 0
7.3774918144441965 [8 8 2 0 2] 8
8.690547658529141 [ 7 10  3  1  0] 10
6.52430481507948 [8 7 2 0 6] 9
17.758563182367105 [17 17  2  0 13] 17
9.046081934804906 [ 6 10  2  0  4] 10
9.93015211107927 [12 10  2  0  2] 11
4.851734802860127 [7 6 1 2 0] 0
16.455194304509206 [18 16  3  0  0] 16
11.920416454654701 [11 12  2  0 10] 13
9.46059136075751 [ 9 10  2  0  2] 9
-0.6648170795759494 [7 0 1 1 0] 0
12.663500805281107 [11 13  2  0  2] 13
7.32244049007504 [8 8 2 0 0] 0
11.049962009289553 [13 11  2  0  2] 11
6.427410342544559 [8 7 1 1 7] 8
11.717965535822724 [12 12  3  0  2] 11
12.353897197730062 [10 13  2  1  6] 13
17.493077844061254 [16 17  1  0  4] 18
9.359122435019414 [ 8 10  2  0  4] 9
9.140650159083924 [11  9  2  0 14] 9
8.505935435654695 [8 9 2 0 8] 10
15.17886415619167 [16 15  3  0  0] 15
4.3804701814160385 [ 6  5  1  1 14] 5
10.884321103537866 [10 11  1  0  8] 10
7.238725942981592 [8 8 3 0 2] 10
10.791972833444204 [11 11  2  0  4] 11
3.468738898467741 [6 5 1 3 0] 0
9.617111610864763 [10 10  2  0  2] 10
5.13787201802363 [6 6 2 0 2] 6
6.195809268344073 [ 6  7  2  1 15] 8
5.955008160560757 [ 7  6  2  0 26] 6
8.286976227074986 [ 8  8  1  0 30] 8
4.284685018658913 [6 5 2 0 6] 6
6.726699667360494 [8 8 1 3 2] 10
11.012178130920828 [11 11  2  0 12] 11
6.046110341757505 [6 7 2 0 0] 0
11.856731407285329 [12 12  2  0  2] 11
17.123197831042383 [17 17  4  0  0] 18
5.34944359250004 [7 6 2 0 4] 6
12.05054860311709 [12 12  1  0  4] 13
15.21616110191618 [15 15  2  0  2] 16
14.023545500692093 [13 14  1  0  0] 14
11.141172718843503 [12 11  2  0 11] 11
16.335971000126463 [16 16  2  0  2] 16
14.709303405869912 [13 15  3  0  0] 15
12.336063441147019 [14 12  1  0  3] 12
7.165920239967788 [7 8 2 0 0] 0
18.123784424869918 [16 18  3  0  2] 18
-0.24511082328659328 [8 0 1 0 0] 0
3.6069895865242065 [3 5 2 1 8] 5
7.958372151982378 [6 9 1 1 4] 8
8.395832786916383 [8 9 2 0 4] 10
9.376876813664062 [ 9 10  3  0  4] 10
14.307922778182308 [15 14  2  0  4] 14
8.598770638392578 [10  9  2  0  0] 0
13.911167730874352 [13 14  3  0  6] 14
15.21616110191618 [15 15  2  0  2] 16
12.782724109663853 [13 13  3  0  0] 14
11.801680082916173 [12 12  2  0  0] 11
8.598770638392578 [10  9  2  0  0] 9
12.976541305495614 [13 13  2  0  2] 13
9.689917313878569 [11 10  3  0  4] 10
14.290168399537658 [14 14  1  0  4] 14
10.8934417591823 [12 11  2  0  2] 12
-0.5581513235011 [6 0 1 0 0] 0
13.554580211371752 [13 13  2  0 23] 13
9.785702476635693 [11 10  2  1 12] 10
7.215774734000192 [9 8 2 1 0] 0
7.067265829759579 [10  8  1  3  3] 7